{% set name = "json-fortran" %}
{% set version = "8.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jacobwilliams/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 16eec827f64340c226ba9a8463f001901d469bc400a1e88b849f258f9ef0d100

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - cmake
    - ninja

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}  # [build_platform == target_platform]
    - test -f $PREFIX/lib/libjsonfortran$SHLIB_EXT  # [unix]

about:
  home: https://github.com/jacobwilliams/json-fortran
  license: BSD-3-Clause AND MIT
  license_file: LICENSE
  summary: Modern Fortran JSON API
  doc_url: https://jacobwilliams.github.io/json-fortran/

extra:
  recipe-maintainers:
    - awvwgk
    - jacobwilliams
